### ISSUE TITLE
JS generation error

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [tpetricek/FunScript.Atom#1]
Hey,

I've only download Your repo and tried to use build

![image](https://cloud.githubusercontent.com/assets/5427083/6779514/05cda414-d15d-11e4-86a2-156d5d98edd9.png)

**Comment by tpetricek** [comment]
No matter what I tried, I was not able to reproduce the error. I have not tried running this from PowerShell console, but:
- Running `build.sh` from Git shell works (and it works on Mac too)
- Running `build.cmd` from normal windows command line works
- Selecting all source and using Alt+Enter in Visual Studio (to send code to F# Interactive) works

I'm not sure why your console output shows the F# Interactive header though. I think recent versions of FAKE use the F# Compiler Service, rather than invoking FSI directly.

**Comment by Krzysztof-Cieslak** [comment]
Both running `build.sh` from Git shell and `build.cmd` from either windows command line or PowerShell fails. Running code from VS F# Interactive works so as for now I can work with it.

FAKE is download using Paket and it's most recent version (3.24.0)
